services:
  web:
    image: ${DOCKERHUB_USERNAME}/observer-backend:${TAG}
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer_network


networks:
  observer_network:
    external: true
