
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-${CONFIG_NAME}
    restart: always
    ports:
      - "${RABBIT_PORT}:5672"     
      - "${RABBIT_UI_PORT}:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - observer_network

  redis:
    image: redis:7-alpine
    container_name: redis-${CONFIG_NAME}
    restart: always
    networks:
    - observer_network

  web:
    image: ${DOCKERHUB_USERNAME}/observer-backend:${TAG}
    container_name: observer-${CONFIG_NAME}
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer_network

  scheduler:
    image: ${DOCKERHUB_USERNAME}/observer-backend:${TAG}
    container_name: scheduler-${CONFIG_NAME}
    restart: always
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    depends_on:
      - rabbitmq
    command: >
      python schedule_run.py
    networks:
      - observer_network

networks:
  observer_network:
    external: true
