services:
  aerich:
    build: .
    command: ["aerich", "upgrade"]
    volumes:
      - .:/app
      - .env:/app/.env 
    environment:
      - TORTOISE_ORM=app.database.config.TORTOISE_ORM
    env_file:
      - .env  
    networks:
      - observer_network

  web:
    #image: ${DOCKERHUB_USERNAME}/crm-backend:${TAG}
    build: .
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs  
      - .env:/app/.env 
    command: >
       gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer_network


networks:
  observer_network:
    driver: bridge
