
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # основной порт
      - "15672:15672"   # UI для админки
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - observer_network

  web:
    image: ${DOCKERHUB_USERNAME}/observer-backend:${TAG}
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      gunicorn -c gunicorn.conf.py run:app
    networks:
      - observer_network

  scheduler:
    image: ${DOCKERHUB_USERNAME}/observer-backend:${TAG}
    restart: always
    volumes:
      - ./logs:/app/logs
      - .env:/app/.env
    command: >
      python schedule_run.py
    networks:
      - observer_network

networks:
  observer_network:
    external: true
